before_script:
  - echo "Welcome to the grader for PA2"
   
after_script:
  - echo "End of Grader"
   
build-and-grade:
  stage: build
  script:
    - cd src
    - make
    - ~/cool-test/test.sh

  tags:
    - pa
   
